Added a nb demonstrating efficient gpu utilizations
redhat-et/foundation-models-for-documentation pull request #44
Opened 2023-05-05 17:36 UTC by suppathak

Related #36 

Exploring:
What happens when we load the models in a lower precision format like INT-8? How is the accuracy, CPU, and memory performance affected? Explain theoretically and show results in a notebook. Touch upon challenges of frameworks like bitsandbytes in production.

2023-05-05 19:38 UTC, Shreyanand commented on notebooks/efficient-gpu-utilization.ipynb
> +{
<p>can we also print the nvidia-smi output?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/redhat-et/foundation-models-for-documentation/pull/44/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2023-06-30 19:21 UTC, Shreyanand commented
@suppathak What is pending in this PR?

2023-06-30 19:26 UTC, suppathak commented
> @suppathak What is pending in this PR?

Thanks @Shreyanand for reminding me . I will clean it a bit and will conclude it. I will add other topics related to model compression in different notebooks.

2023-07-04 15:39 UTC, Shreyanand commented on notebooks/efficient-gpu-utilization.ipynb
> +{
<p>source?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/redhat-et/foundation-models-for-documentation/pull/44/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2023-07-04 15:39 UTC, Shreyanand commented on notebooks/efficient-gpu-utilization.ipynb
> +{
<p>Do you mean <strong>with</strong> quantization? </p><p>Can you provide the percentage change in memory and inference time? it is more intuitive.</p><p>For inference time computation, can you run the cell 10 times and average the time? That makes the result more robust.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/redhat-et/foundation-models-for-documentation/pull/44/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2023-07-04 15:41 UTC, Shreyanand requested changes
Requested some minor changes, majorly around adding source of the images and improving results. 
Also, add this notebook in the resource section in the README.

2023-12-12 21:17 UTC, suppathak commented
@Shreyanand , Is this good to merge? Lmk if you have any feedback. Thanks.

2024-03-22 16:38 UTC, Shreyanand approved these changes

2024-03-22 16:38 UTC, merged